### ISSUE TITLE
Dependency on http://grok.zope.org/releaseinfo/current

### ISSUE THREAD

**Issue by michaelthamm** [zopefoundation/grok#2]
$grokproject helloworld
Determining current grok version...
Error: cannot download required http://grok.zope.org/releaseinfo/current
Server may be down.  Please try again later.

The server is up and returns 1.5.5 in a browser. 
May be related to openssl for python Python 2.7.6 bugs
** 2.7.11 works fine **
Looks like all zope.org server issues. can't build a project either. 
Couldn't this not be a requirement to create a new project?
Maybe put a file or env var somewhere with the value if unable to connect?

**Comment by ulif** [comment]
While I see your problems (`grokproject` is really outdated; and so is grok.zope.org. 1.5.5 was the "current" grok release in 2011), I think this is mainly a `grokproject` issue. Not a `grok` issue.

Would you mind to repeat the issue at https://github.com/zopefoundation/grokproject/ ?

I am glad to discuss changes there then.

**Comment by michaelthamm** [comment]
Sure - that makes sense.
