### ISSUE TITLE
Documentation referencing grokproject, while grokproject is no longer maintained

### ISSUE THREAD

**Issue by minigraphx** [zopefoundation/grok#22]
## BUG/PROBLEM REPORT / FEATURE REQUEST

At the moment I try to understand zope, grok etc. 
I'm using python3, and while grok is updated for python3, grokproject is not.
So getting started is no longer possible using grokproject

### What I expect to happen:

Find some kind of getting started or a usage documentation.

**Comment by icemac** [comment]
This is because `grok` currently does not support to be used for new projects. Sorry.
You might look into https://github.com/zopefoundation/grok/tree/master/grokwiki as an example app. (After merging #20, it will work again.)
