### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/grok#3]
Tasks:
- [ ] Inventorize the status of Python 3  in Grok
- [ ] Make a plan how to port Grok (what steps are needed to run Grok on Python 3?)
- [ ] Do the actual porting.

**Comment by kulll** [comment]
Awesome

**Comment by icemac** [comment]
@janjaapdriessen @janwijbrand What is the status of this issue? Did you complete any other the tasks during the sprint?

**Comment by janwijbrand** [comment]
This issue is not finished. We need to continue the "grunt" work of updating package-by-package against a Python-3-compatible ZTK and (mostly) fixing tests.

**Comment by icemac** [comment]
All grok packages I know have been ported, so closing this issue.
