### ISSUE TITLE
zope.app.dublincore.view permission renamed to zope.dublincore.view

### ISSUE THREAD

**Issue by prsephton** [zopefoundation/grok#8]
The zope.dublincore-4.1.1-py2.7.egg package underwent changes on 2010-08-19 where zope.app.dublincore.* shims were removed and replaced with zope.dublincore.**

Some dependency has clearly changed to subsequently use the new zope.dublincore release.

The default etc/site.zcml.in still contains a reference to zope.app.dublincore.view

Simply changing that to zope.dublincore.view did not work.  (how come?).  The server would only run after commenting that permission grant line out completely.

**Comment by icemac** [comment]
@prsephton Do you feel comfortable to write a PR for this issue?

**Comment by prsephton** [comment]
I think simply removing (commenting out) the permission will have other repurcussions.  The right way to fix it would be to add the correct permission (zope.dublincore.view) to the zcml, but I am not smart enough to know why that (just replacing _zope.app.dublincore.view_ with _zope.dublincore.view_) breaks.  

That's why I provided the information, but made no attempt at a PR - for fear of doing the wrong thing.

I don't mind going digging myself if no one else has an instant insight.
